// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CalculateOptimalClusters(arg1:string):Promise<number>;

export function ConvertFilesToWAV(arg1:string):Promise<void>;

export function CreateProject(arg1:string):Promise<string>;

export function CreateProjectFolder():Promise<string>;

export function GetProjectData(arg1:string):Promise<main.ProjectData>;

export function Greet(arg1:string):Promise<string>;

export function ListFilesInDirectory(arg1:string):Promise<string>;

export function ListProjects():Promise<Array<string>>;

export function LogError(arg1:string,arg2:Error,arg3:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function ProcessAudioChunksAndSpectrograms(arg1:string):Promise<Array<string>>;

export function SaveSelectedDirectory(arg1:string,arg2:string):Promise<void>;
