// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFilesToWAV(arg1) {
  return window['go']['main']['App']['ConvertFilesToWAV'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateProjectFolder() {
  return window['go']['main']['App']['CreateProjectFolder']();
}

export function GetProjectData(arg1) {
  return window['go']['main']['App']['GetProjectData'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFilesInDirectory(arg1) {
  return window['go']['main']['App']['ListFilesInDirectory'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SaveSelectedDirectory(arg1, arg2) {
  return window['go']['main']['App']['SaveSelectedDirectory'](arg1, arg2);
}
